##
## Cloudflare Pages 配置文件
##
name = "znote"
account_id = "9dea4d4c91be88e92ffe5a553a0d6980"
workers_dev = false
compatibility_date = "2026-03-03"

[build]
command = "npm run build"
cwd = "."

[assets]
directory = "docs/.vuepress/dist"

[pages]
### Cloudflare Page 如果有根路径问题，使用重定向解决 ###
#
# 1. 登录 Cloudflare 控制台
# 2. 选择您的域名
# 3. 点击 "Rules" → "Page Rules"
# 4. 创建重定向规则 ：
#   - URL Pattern : `https://yourdomain.com/znote/*`
#   - Forwarding URL → 301 Redirect
#   - Destination URL : `https://yourdomain.com/${1}`

[env]
