# Cloudflare Pages 配置文件
name = "znote"
account_id = "9dea4d4c91be88e92ffe5a553a0d6980"
workers_dev = false
compatibility_date = "2026-03-03"

[build]
command = "npm run build"
cwd = "."

[assets]
directory = "docs/.vuepress/dist"

[pages]

[env]
